builds:
  - main: .
    binary: corpass
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    ldflags: |
      -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -extldflags '-static'
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
archives:
- format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
